# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configura o Node.js e o cache do NPM em um único passo
      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Configura o cache para o gerenciador de pacotes npm
          # Isso acelera as instalações futuras
          cache: 'npm'

      # 3. Instala as dependências do projeto
      - name: Install Dependencies
        run: npm install

      # 4. Executa o lint para verificar a qualidade do código
      - name: Run Lint
        run: npm run lint

      # 5. Executa o build utilizando Turborepo
      - name: Build packages
        run: npm run build

      # 6. SUGESTÃO: Adicione um passo de teste
      # O nome do seu job é "build_and_test", então um passo de teste é esperado.
      # Se você tiver testes, adicione o comando aqui.
      - name: Run Tests
        run: npm run test # ou o comando que você usa para rodar testes
