# .github/workflows/ci.yml

name: CI

# Define quando o workflow deve ser executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    # Define o sistema operacional que será usado
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a versão do Node que seu projeto utiliza

      # 3. Instala o npm (se necessário, embora geralmente venha com o Node)
      #    e configura o cache para as dependências
      - name: Install npm and Cache Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 4. Instala as dependências do projeto
      - name: Install Dependencies
        run: npm install

      # 5. Executa o lint para verificar a qualidade do código
      - name: Run Lint
        run: npm run lint

      # 6. Executa o build utilizando Turborepo
      #    O turbo já usará o cache local e remoto (se configurado)
      - name: Build packages
        run: npm run build
